# Groups the generated release notes by pull request label.
changelog:
  exclude:
    authors: [dependabot]
  categories:
    - title: New features
      labels: [enhancement]
    - title: Fixes
      labels: [bug]
    - title: Other changes
      labels: ["*"]
